### ISSUE TITLE
 Config Error  Invalid notificationChannelID. Must be a channel ID from a server  you are in..

### ISSUE THREAD

**Issue by suprix** [TheRacingLion/Discord-SelfBot#38]
![image](https://user-images.githubusercontent.com/24485754/27919367-cc17b82e-6271-11e7-965e-432be46fbcae.png)
So I setup config.json, added my ID and discord token but I am getting this error, here is my config:
![image](https://user-images.githubusercontent.com/24485754/27919426-f12944e8-6271-11e7-8b39-ad64c15ae39f.png)

**Comment by TheRacingLion** [comment]
@suprix Well, like it says in the console, your `notificationChannelID` field in the config needs to be the ID of a channel you are in. Since you set the `mentionNotificator` and the `keywordNotificator` both to `true`, the bot needs a channel to post the information in. Just change the `notificationChannelID` field in the config to the ID of the channel you want to get notified in.
