### ISSUE TITLE
Good Bye message logging

### ISSUE THREAD

**Issue by alktbihd** [TheRacingLion/Discord-SelfBot#55]
> 2.4 End User Data.
> “End User Data” means all data associated with the content within the functionality enabled by the API or SDK, including but not limited to message content, message metadata, voice data and voice metadata. You acknowledge and agree that Discord and its end users, as applicable, retain all worldwide right, title and interest in and to the End User Data. If you have access to End User Data, you shall ensure that your Applications do not collect, use and/or disclose End User Data except (a) as necessary to exercise your rights under this Agreement, (b) as expressly permitted by the End Users, and (c) in accordance with Discord’s Privacy Policy. You shall not sell, license or otherwise commercialize any End User Data. You may not use End User Data to target End Users for marketing or advertising purposes. You may not disclose End User Data to any ad network, data broker or other advertising or monetization related service. You shall permanently delete all End User Data upon Discord’s or the End User’s request and within seven (7) days following the End User’s termination of the End User’s account. You may only retain chat logs as necessary for the operation of your Applications. Discord’s offering of an API or SDK that allows you to reproduce or display End User message content is not an express or implied license to such content from Discord. You must seek permission from End Users.
> **This means that any bot that logs messages or even stores user IDs now breaks the terms of service, unless it explicitly asks the user it's logging for permission. This outlaws logging bots, bots with features like temp ban, bots which reassign roles when rejoining, etc.**
Source: [The New TOS](https://discordapp.com/developers/docs/legal)

**Comment by TheRacingLion** [comment]
Its a selfbot? It runs on the user's account. Any data the user has access to, the selfbot will have access to it as well. The selfbot does not store any data from discord. Discord already as a feature that notifies a user when he was mentioned. All the notifications on this selfbot are "send and forget" type. Meaning no data is actually stored. I believe that since this runs on a user account, the user is responsible for it, meaning it is subject to the same Terms of service (of the user, not the api). All the data that the selfbot exposes in notifications can also be seen in discord itself (meaning the user already gets access to this data?) by the user himself if he chooses to.
Please correct me on ANY of this if I am wrong. But I only provide an app (not even the app itself, just the code and tools to run it), and since it runs on your own account you are responsible for it? The new TOS as I see it, is only directed to active discord bots that run on a server, and not the user account.
