### ISSUE TITLE
Selfbots are bannable

### ISSUE THREAD

**Issue by TehPers** [TheRacingLion/Discord-SelfBot#68]
Discord's current policy is to ban selfbots. Since this result appears first on google when searching "discord selfbot rules", I think it'd be beneficial to update the README with that information to avoid confusion.

**Comment by TehPers** [comment]
Relevant article: https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

**Comment by TheRacingLion** [comment]
I only offer a service, I am not responsible for what people do with it, like I state multiple times in the README. Anyone that is on discord and knows what a selfbot is, also knows discord doesn't support them and they can be banned if found. This is been a issue ever since selfbots were a thing on discord.
