### ISSUE TITLE
eris, module, disconnect error

### ISSUE THREAD

**Issue by skye-fs** [TheRacingLion/Discord-SelfBot#77]
Edited the config file.
Opened installer.bat.
Installed installer.bat.
Seen run.bat.

When I tried to open run.bat normally, it shows this. Everything seems successful, commands load etc. But when I typed *help in discord, nothing happens. And a few seconds later, it says Disconnected from discord, as seen in the screenshot below.
![disconnect_error](https://user-images.githubusercontent.com/39058978/39823281-c4f4c19c-53d2-11e8-869f-e60a0a0319cd.PNG)

What I tried to do next was open run.bat as administrator. As a result, it shows this. 
Error: Cannot find module 'C\Windows\system32\self.js'. So I saw a self.js in the SelfBot folder, and I copied and pasted it into the directory above. As seen in the screenshot below.
![module_error](https://user-images.githubusercontent.com/39058978/39823474-2731c792-53d3-11e8-87a6-25a3a1183a96.PNG)

What happened after pasting self.js was this. Again, I open run.bat as administrator. 
![eris_error](https://user-images.githubusercontent.com/39058978/39823630-74350e8c-53d3-11e8-9cdd-5f22db41f50a.PNG)
Error: Cannot find module 'eris'
and alot of at Function.Module._resolveFilename (module.js:547:15) and similar errors (in the screenshot above).

So.. I'm not sure why this is happening and what is the error. None of these errors appear when I open run.bat normally BUT, it says "disconnected from discord" after a while. Is there a solution/fix to this?

**Comment by TheRacingLion** [comment]
When you run something as administrator it sets the current directory to `C\Windows\system32` and since that wasn't the location of the selfbot installation when running `installer.bat` it said there was nothing there (which is correct). The better choice to do here isn't copying over the files to that directory, because the `installer.bat` had already ran in the previous location, and besides, the selfbot doesn't require admin permissions as far as I am concerned. If the `Disconnected from Discord` message appeared, I would double-check the token in the config, make sure the prefix in config is indeed the same one you are using, and make sure the problem is not your internet connection causing it to randomly disconnect. Does this also happen every time you run the selfbot? Also for future stuff, whenever you see a `Cannot find module 'X'` that usually means you need to `npm install X` or if its selfbot stuff just `npm i` and that will install all stuff for you (which is basically what `installer.bat` does).

**Comment by skye-fs** [comment]
Thank you for the clarification of running as administrator. Yes, I have checked the config file. Everything is setup. I also did "npm i" and says up to date. But the problem still occurs when I open run.bat. Also it's not my internet connection because I'm torrenting at 4mbs.
![image](https://user-images.githubusercontent.com/39058978/39876310-d3f05b0e-5498-11e8-9ac6-6dd1b9d4235f.png)

**Comment by skye-fs** [comment]
I left the terminal opened for a while and then it says BOT ERROR. I don't understand the error.
![image](https://user-images.githubusercontent.com/39058978/39877052-e0fba5ea-549a-11e8-9d75-14aed7eeba8b.png)

**Comment by TheRacingLion** [comment]
That error is when the bot finds a keyword after it disconnected once before already, but I think it isn't related to the disconnection happening itself. It is still really weird to me why it just disconnects like that. And you said it never does anything when you type something in discord? Auto-reconnect is enabled on the selfbot and that explains why it keeps doing it over and over, but not why it disconnects in the first place.

**Comment by skye-fs** [comment]
Yes. My prefix is * and when I typed *help nothing happens.

**Comment by Snrubyy** [comment]
I'm currently having the very same error, dunno anything I can do to fix it. Skye, if you've found a way to fix it, I'm all ears. RacingLion, if you've found a way, still all ears. Thanks!

**Comment by skye-fs** [comment]
Still have the problem. I was waiting for a reply from TheRacingLion for a fix probably.
